# SPDX-License-Identifier: GPL-3.0-or-later
# Ein/Aus-Taster (GPIO3, dtoverlay=gpio-shutdown) gegen versehentliches Ausschalten schützen:
# kurzer Druck wird ignoriert, langer Druck (systemd-logind: 5 s) fährt sauber herunter.
# Einschalten aus dem Halt erledigt der Bootloader (kurzer Druck genügt).
# Installation: tools/ein_aus_einrichten.sh → /etc/systemd/logind.conf.d/sopho2sip-ein-aus.conf
[Login]
HandlePowerKey=ignore
HandlePowerKeyLongPress=poweroff
