; SPDX-License-Identifier: GPL-3.0-or-later
[modules]
autoload = yes
; nicht gebraucht (nur PJSIP)
noload = chan_iax2.so
noload = chan_unistim.so
noload = chan_mgcp.so
noload = chan_skinny.so
noload = res_pjsip_phoneprov.so
noload = res_phoneprov.so
noload = cdr_custom.so
noload = cdr_manager.so
noload = cel_custom.so
