; SPDX-License-Identifier: GPL-3.0-or-later
; SIP-Konten: "gateway" = baresip auf dem Pi (Leitung zur Sopho), "tel1"/"tel2" = Softphones bzw. Nextcloud-App.
; Zugangsdaten stehen nur auf dem Pi in pjsip_konten.conf (erzeugt von tools/asterisk_config.sh).
; Netzbeschränkung: Firewall (SIP/RTP nur aus 130.75.63.128/25 und VPN) und zusätzlich ACL unten.

[global]
type = global
user_agent = Sopho2SIP
endpoint_identifier_order = auth_username,username,ip

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[transport-tcp]
type = transport
protocol = tcp
bind = 0.0.0.0:5060

[acl]
type = acl
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.0/8
permit = 130.75.63.128/25
permit = 10.8.6.0/24

; --- Vorlagen ---------------------------------------------------------------------------------------
[endpunkt](!)
type = endpoint
disallow = all
allow = alaw,ulaw
direct_media = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
dtmf_mode = rfc4733
send_pai = yes
trust_id_outbound = yes

[zugang](!)
type = auth
auth_type = userpass

[adresse](!)
type = aor
max_contacts = 3
remove_existing = yes
qualify_frequency = 60

#include pjsip_konten.conf
